/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FlowdockThreadURL = string;
export type Status = "open" | "ongoing" | "closed" | "archived";

export interface BrainstormTopic {
  name: string;
  data: {
    reporter: string;
    category: string;
    description: string;
    flowdockThreadUrl?: FlowdockThreadURL;
    participants?: unknown[];
    mentionsUser?: unknown[];
    alertsUser?: unknown[];
    mentionsGroup?: unknown[];
    alertsGroup?: unknown[];
    status?: Status;
    [k: string]: unknown;
  };
  tags?: string[];
  [k: string]: unknown;
}
