/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CheckInDateTime = string;
export type Review = boolean;
export type TimeUntilNextCheckin = TimeUntilNextCheckin1 & TimeUntilNextCheckin2;
export type TimeUntilNextCheckin1 = number;
export type TimeUntilNextCheckin2 = Day | Week | Week | Weeks | Month | Months;
export type Day = 86400;
export type Week = 345600;
export type Week = 604800;
export type Weeks = 1209600;
export type Month = 2419200;
export type Months = 7257600;
export type LengthOfNextCheckin = LengthOfNextCheckin1 & LengthOfNextCheckin2;
export type LengthOfNextCheckin1 = number;
export type LengthOfNextCheckin2 = Minutes | Minutes1 | Minutes2;
export type Minutes = 600;
export type Minutes1 = 1800;
export type Minutes2 = 3000;
export type ExtraAttendeesNeeded = {
  user?: string;
  role?: "owner" | "guide" | "dedicated" | "contributor" | "observer";
  [k: string]: unknown;
}[];
export type UnnecessaryAttendees = string[];

export interface Checkin {
  name?: string;
  tags?: string[];
  data: {
    datetime?: CheckInDateTime;
    is_review?: Review;
    interval_to_next?: TimeUntilNextCheckin;
    length_of_next?: LengthOfNextCheckin;
    minutes?: string;
    extra_attendees_needed?: ExtraAttendeesNeeded;
    unnecessary_attendees?: UnnecessaryAttendees;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
