/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String = string;
export type Array = [string, ...string[]];

export interface Contact {
  markers?: string[];
  name?: string | null;
  slug?: string;
  data: {
    source?: string;
    profile?: {
      email?: String | Array;
      company?: string;
      title?: string;
      type?: string;
      country?: string;
      city?: string;
      name?: {
        first?: string;
        last?: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
