/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ExternalEvent {
  slug: string;
  data: {
    source: string;
    headers: {
      [k: string]: unknown;
    };
    payload:
      | {
          [k: string]: unknown;
        }
      | string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
