/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Message {
  version: "1.0.0";
  data: {
    timestamp: string;
    actor: string;
    payload: {
      mentionsUser?: string[];
      alertsUser?: string[];
      mentionsGroup?: string[];
      alertsGroup?: string[];
      file?: {
        name?: string;
        mime?: string;
        bytesize?: number;
        slug?: string;
        [k: string]: unknown;
      };
      attachments?: {
        url: string;
        name: string;
        mime: string;
        bytesize: number;
        [k: string]: unknown;
      }[];
      message: string;
      [k: string]: unknown;
    };
    edited_at?: string;
    /**
     * Users that have seen this message
     */
    readBy?: string[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
