/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Status = "Created" | "Discovery" | "Evaluation" | "Committed " | "Closed Won" | "Closed Lost";
export type ExpectedCloseDate = string;
export type EstimatedRecurringValue = number;
export type EstimatedNonRecurringValue = number;
export type TotalValue = number;
export type DeviceType = string;
export type UseCaseS = string;
export type TechStack = string;

export interface Opportunity {
  name?: string;
  data?: {
    status: Status;
    dueDate?: ExpectedCloseDate;
    recurringValue?: EstimatedRecurringValue;
    nonRecurringValue?: EstimatedNonRecurringValue;
    totalValue?: TotalValue;
    device?: DeviceType;
    usecase?: UseCaseS;
    stack?: TechStack;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
