/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Phase = Phase1 & Phase2;
export type Phase1 =
  | Proposed
  | Waiting
  | ResearchingDraftingSpec
  | CandidateSpec
  | AssignedResources
  | Implementation
  | AllMilestonesCompleted
  | FinalisingAndTesting
  | Merged
  | Released
  | DeniedOrFailed;
export type Proposed = "proposed";
export type Waiting = "waiting";
export type ResearchingDraftingSpec = "researching";
export type CandidateSpec = "candidate-spec";
export type AssignedResources = "assigned-resources";
export type Implementation = "implementation";
export type AllMilestonesCompleted = "all-milestones-completed";
export type FinalisingAndTesting = "finalising-and-testing";
export type Merged = "merged";
export type Released = "released";
export type DeniedOrFailed = "denied-or-failed";
export type Phase2 = string;

export interface ProductImprovement {
  name: string;
  data: {
    description?: string;
    specification?: string;
    phase: Phase;
    participants?: unknown[];
    mentionsUser?: unknown[];
    alertsUser?: unknown[];
    mentionsGroup?: unknown[];
    alertsGroup?: unknown[];
    [k: string]: unknown;
  };
  tags?: string[];
  [k: string]: unknown;
}
