/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Version = "1.0.0";
export type Timestamp = string;
export type Actor = string;
export type Message = string;
export type Comment = string;
export type Score = number;
export type EditedAt = string;
export type UsersThatHaveSeenThisRating = string[];

export interface Rating {
  version: Version;
  data: {
    timestamp: Timestamp;
    actor: Actor;
    payload: {
      mentionsUser?: string[];
      alertsUser?: string[];
      mentionsGroup?: string[];
      alertsGroup?: string[];
      message?: Message;
      comment?: Comment;
      score?: Score;
      [k: string]: unknown;
    };
    edited_at?: EditedAt;
    readBy?: UsersThatHaveSeenThisRating;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
