/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Repository {
  name?: string;
  data: {
    owner?: string;
    name?: string;
    git_url?: string;
    html_url?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
