/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Summary {
  version: "1.0.0";
  data: {
    timestamp: string;
    actor: string;
    payload: {
      mentionsUser?: string[];
      alertsUser?: string[];
      mentionsGroup?: string[];
      alertsGroup?: string[];
      message: string;
      [k: string]: unknown;
    };
    /**
     * Users that have seen this summary
     */
    readBy?: string[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
