/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CurrentStatus = string;
export type Status = "open" | "closed" | "archived";

export interface SupportThread {
  name?: string | null;
  data: {
    category?: "general" | "customer-success" | "devices" | "fleetops" | "security";
    tags?: string[];
    mirrors?: string[];
    environment?: "production";
    description?: string;
    inbox?: string;
    statusDescription?: CurrentStatus;
    participants?: unknown[];
    mentionsUser?: unknown[];
    alertsUser?: unknown[];
    mentionsGroup?: unknown[];
    alertsGroup?: unknown[];
    status?: Status;
    [k: string]: unknown;
  };
  tags?: string[];
  [k: string]: unknown;
}
