/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Severity = "high" | "medium" | "low";
/**
 * The OS version that this issue was fixed in (if applicable)
 */
export type FixedInOSVersion = string;
/**
 * The supervisor version that this issue was fixed in (if applicable)
 */
export type FixedInSupervisorVersion = string;
export type AffectedOSVersions = string[];
export type AffectedSupervisorVersions = string[];
export type Category = string;
/**
 * Can this information be made publicly available?
 */
export type Shareable = boolean;

export interface SupportIssue {
  name: string;
  data?: {
    severity?: Severity;
    fixedInOSVersion?: FixedInOSVersion;
    fixedInSupervisorVersion?: FixedInSupervisorVersion;
    affectedOSVersions?: AffectedOSVersions;
    affectedSupervisorVersions?: AffectedSupervisorVersions;
    category?: Category;
    shareable?: Shareable;
    Problem?: string;
    Solution?: string;
    participants?: unknown[];
    mentionsUser?: unknown[];
    alertsUser?: unknown[];
    mentionsGroup?: unknown[];
    alertsGroup?: unknown[];
    [k: string]: unknown;
  };
  tags?: string[];
  [k: string]: unknown;
}
