/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Thread {
  data?: {
    description?: string;
    participants?: unknown[];
    mentionsUser?: unknown[];
    alertsUser?: unknown[];
    mentionsGroup?: unknown[];
    alertsGroup?: unknown[];
    [k: string]: unknown;
  };
  tags?: string[];
  [k: string]: unknown;
}
