/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WebPushSubscription {
  data: {
    endpoint: string;
    token: string;
    auth: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
