/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Status = "draft" | "candidate" | "complete";

export interface Workflow {
  name?: string | null;
  tags?: string[];
  data?: {
    status?: Status;
    loop?: string;
    lifecycle?: string;
    description?: string;
    diagram?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
